---
title: "Plotly"
output:
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

This page is about making some Plotly examples

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


Let's look atNYC airbnb data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, stars, price, room_type, lat, long) %>%
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500) %>% 
  drop_na(stars)
```

## Make a scatterplot

Here's a plotly scatterplot!

```{r}
nyc_airbnb %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers"
  )
```


```{r}
nyc_airbnb %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers", color = ~price, alpha = .5
  )
```


```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Price: $", price, "\nStars:", stars)
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers", color = ~price, text = ~text_label, alpha = .5
  )
```










